import React, { useContext } from 'react';

import { ThemeContext } from '@local/contexts/theme';
import { getLayout } from '@local/hoc/layout';
import Head from 'next/head';

export default function Dashboard() {
  const { isDark } = useContext(ThemeContext);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Dashboard the theme is {isDark ? 'dark' : 'light'}</div>
    </div>
  );
}

Dashboard.getLayout = getLayout;
