import React, { useContext } from 'react';

import { ThemeContext } from '@local/contexts/theme';
import { getLayout } from '@local/hoc/layout';
import Head from 'next/head';

import { DwButton } from '@darkwilly08/dw-button';

export default function Settings() {
  const { isDark, toggleTheme } = useContext(ThemeContext);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <DwButton onClick={() => toggleTheme((prev) => !prev)} text={`the theme is ${isDark ? 'dark' : 'light'}`} />
    </div>
  );
}

Settings.getLayout = getLayout;
